config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  mount_uploader :image, ImageUploader
  default_scope -> { order(created_at: :desc) }
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid? || @blog.id == "confirm"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog">
    <div class="title-tag">
      <%= form.label :title, "タイトル", class: "title-text" %>
    </div>
    <div class="title-field-tag">
      <%= form.text_field :title, class: "title-field" %>
    </div>
    <br></br>
    <div class="content-tag">
      <%= form.label :content, "本文", class: "content-text" %>
    </div>
    <div class="content-field-tag">
      <%= form.text_field :content, class: "content-field" %>
    </div>
    <br></br>
      <label class="image">
        <svg xmlns="http://www.w3.org/2000/svg" width="70" height="30" fill="green" class="bi bi-file-earmark-image" viewBox="0 0 16 16">
          <path d="M6.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
          <path d="M14 14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5L14 4.5V14zM4 1a1 1 0 0 0-1 1v10l2.224-2.224a.5.5 0 0 1 .61-.075L8 11l2.157-3.02a.5.5 0 0 1 .76-.063L13 10V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4z"/>
        </svg>
        <div class="image-form">
        <%= form.file_field :image %>
      </div>
        </label>
        <div class="image_tag">
          <%= form.label :image, "写真を選択", class: "image-text" %>
    </div>
  </div>
  <br>
  <div class="create-btn-area">
    <%= form.submit "投稿", class: "create-btn" %>
  </div>
<% end %>
<br>
<div class="blog_url">
  <%= link_to "ブログ一覧画面にもどる", blogs_path, class: "cp_link" %>
</div>

app/views/blogs/confirm.html.erb
<div class="header">
  <h3>以下の内容で、送信する。</h3>
</div>
<div class="confirm-box">
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <div class="confirm-title-box">
    <p class="confirm-title">タイトル:<%= @blog.title %></p>
  </div>
      <p class="confirm-content"><%= @blog.content %></p>
      <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
</div>
<div class="confirm-btn-area">
<%= form.submit "登録する", class: "submit-btn" %>
    <%= form.submit "戻る", name: 'back', class: "return-btn" %>
<% end %>
</div>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
 <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<div class="blog_url">
  <%= link_to '新しくブログを投稿する', new_blog_path, class: "cp_link" %>
</div>
    <% @blogs.each do |blog| %>
    <div class="index-box">
      <div class="index-user-name">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
        <p class="user-name-text"><%= blog.user.name %></p>
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="20" fill="gray" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
          <path d="M12.14 8.753l-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
        </svg>
        <p class="blog-title">タイトル:<%= blog.title %></p>
      </div>
      <div class="content-box">
        <p class="blog-content"><%= blog.content %></p>
      </div>
      <div class="index-image-area">
      <% if blog.image.present? %>
        <%= image_tag blog.image.url, class: "index-image" %>
      <% else %>
        <%= image_tag('noimage.png', class: "index-image" ) %>
      <% end %>
      </div>
      <br></br>
      <%= link_to '詳細を確認する', blog_path(blog.id), class: "index-link" %>
      <%= link_to "ブログを編集する", edit_blog_path(blog.id), class: "index-link" %>
      <%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "index-link"%>
    </div>
  <% end %>

app/views/blogs/new.html.erb
<div class="header">
  <h2 class="new-header">投稿を作成</h2>
  <div class="new-blog-box">
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="header">
  <h1>ブログ詳細画面</h1>
</div>
<div class="title_text">
  <p>タイトル: <%= @blog.title %></p>
</div>
<div class="image_area">
  <div class="image">
    <p><%= image_tag @blog.image.url %></p>
  </div>
</div>
<div class="content_text">
  <p>内容: <%= @blog.content %></p>
</div>
<br>
<div class="blog_url">
  <%= link_to "ブログ一覧画面にもどる", blogs_path, class: "cp_link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <header>
        <h1 class="header-text">facebook</h1>
        <% if logged_in? %>
        <div class="head-link">
          <%= link_to "プロフィール", user_path(current_user.id), class: "profile-link" %>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "logout-link" %>
        </div>
        <% else %>
        <div class="head-link">
          <%= link_to "新規登録", new_user_path, class: "signup-link" %>
          <%= link_to "ログイン", new_session_path, class: "login-link" %>
        </div>
        <% end %>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}")%>
        <% end %>
        <%= yield %>
      </div>
    </header>
</html>

app/views/users/new.html.erb
<div class="signup-header">
  <h1>新規登録</h1>
  <h9>入力してください</h4>
</div>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2 class="error-massage">
      <%= pluralize(@user.errors.count,"箇所のエラー") %> があります。 <%= @user.name %>
    </h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <div class="signup-field">
    <div class="name-tag">
      <%= f.label :name,"お名前", class: "login-name" %>
    </div>
    <div class="new-name">
      <%= f.text_field :name, class: "name-field" %>
    </div>
    <br></br>
    <div class="email-new-tag">
      <%= f.label :email,"メールアドレス", class:"login-email" %>
    </div>
    <div class="new-email">
      <%= f.email_field :email, class: "new-email-field" %>
    </div>
    <br></br>
    <div class="password-new-tag">
      <%= f.label :password,"パスワード", class: "login-password" %>
    </div>
    <div class="new-password">
      <%= f.password_field :password, class: "new-password-field" %>
    </div>
    <br></br>
    <div class="password-confirmation-tag">
      <%= f.label :password_confirmation,"パスワードの確認", class: "login-password-confirmation" %>
    </div>
    <div class="password-confirmation">
      <%= f.password_field :password_confirmation, class: "password-confirmation-field" %>
    </div>
  </div>
  <br></br>
  <div class="login">
    <%= f.submit "アカウント作成", class: "login_btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="header">
  <h1 class="user-name"><%= @user.name %></h1>
</div>
<br>
<div class="user-info-box">
  <div class="user-info">
    <p class="info-text">メールアドレス<p>
    <p class="info-mail"><%= @user.email %></p>
  </div>
</div>
<br>
<div class="user-info-box">
  <div class="blog-box">
    <div class="icon">
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#136FFF" class="bi bi-plus-circle" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
    </svg>
  </div>
  <div class="new-blog">
    <div class="new-blog-link">
      <%= link_to '新しいブログを投稿', new_blog_path, class: "blog-link" %>
    </div>
    <div class="new-blog-text">
      <p>写真やメッセージを投稿しよう</p>
    </div>
  </div>
  </div>
</div>